wandb_version: 1

gitlog:
  desc: null
  value: ' '
net:
  desc: null
  value: lenet
use_sigmoid:
  desc: null
  value: relu
data_path:
  desc: null
  value: ~/data/CIFAR10
logdir:
  desc: null
  value: ./logs\2023-05-05-08-33-50_lenet-84_2_0_0.1-0.0005-none-1.0-0.9-none-1.0-0.9-none-128_fedavg-0_dirichlet-0.1_relu_50
group_name:
  desc: null
  value: group
project:
  desc: null
  value: project-ktboi
embedding_dim:
  desc: null
  value: 84
data_seed:
  desc: null
  value: 0
seed:
  desc: null
  value: 0
num_workers:
  desc: null
  value: 2
dirichlet:
  desc: null
  value: true
alpha:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.1
lr_scheduler:
  desc: null
  value: none
lr_gamma:
  desc: null
  value: 1.0
lr_alpha:
  desc: null
  value: 0.9
lr_decay:
  desc: null
  value: none
lrl2_gamma:
  desc: null
  value: 1.0
lrl2_alpha:
  desc: null
  value: 0.9
lrl2_decay:
  desc: null
  value: none
weight_decay:
  desc: null
  value: 0.0005
per_layer_lr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 128
lamda:
  desc: null
  value: 0.5
lamda_l2:
  desc: null
  value: 0.5
num_epochs:
  desc: null
  value: 50
use_transfer_until:
  desc: null
  value: 50
use_weight_transfer_after:
  desc: null
  value: 0
normalize:
  desc: null
  value: false
mean_computation_dataset:
  desc: null
  value: train-subset
mean_computation_batch_size:
  desc: null
  value: 128
shuffle:
  desc: null
  value: 'False'
share_last_layer:
  desc: null
  value: false
weighted_sharing:
  desc: null
  value: false
hetero_arch:
  desc: null
  value: false
active_ratio:
  desc: null
  value: 1.0
transfer:
  desc: null
  value: fedavg
leftout_worker_id:
  desc: null
  value: 0
num_moments:
  desc: null
  value: 1
compute_divergence:
  desc: null
  value: false
discr_comp_interval:
  desc: null
  value: 50
resume:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683300831.397145
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.0
      5: 0.15.1
      8:
      - 3
      - 8
